config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:index] do
    resources :comments, only: [:new, :create]
  end

  post 'upvote' => 'votes#upvote', as: :upvote
  post 'downvote' => 'votes#downvote', as: :downvote

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, uniqueness: true

  has_many(
    :moderated_subs,
    class_name: "Sub",
    foreign_key: :moderator_id,
    primary_key: :id
  )

  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id
  )

  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :author_id,
    primary_key: :id
  )

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(username,password)
    user = User.find_by_username(username)
    if user
      return user if user.valid_password?(password)
    else
      nil
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    render :show
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>
    Username
    <input type="text" name="user[username]" value="<%= @user.username%>"%>
  </label>

  <label>
    Password
    <input type="password" name="user[password]">
  </label>

  <button>Sign Up</button>

</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<a href="<%= new_sub_url %>">Create Sub</a>
<br>
<a href="<%= new_post_url %>">Create Post</a>
<br>

<h2>Posts</h2>

<ul>
<% @posts.each do |post| %>
  <li>
    <a href="<%= post_url(post) %>"><%= post.title %></a>
  </li>
  <br>
<% end %>
</ul>