config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:index] do
    resources :comments, only: [:new, :create]
  end

  post 'upvote' => 'votes#upvote', as: :upvote
  post 'downvote' => 'votes#downvote', as: :downvote

end

app/models/sub.rb
class Sub < ActiveRecord::Base

  validates :title, :description, :moderator, presence: true

  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id
  )

  has_many(
    :posts,
    through: :post_subs,
    source: :post
  )

  has_many(
    :post_subs,
    class_name: "PostSub",
    foreign_key: :sub_id,
    primary_key: :id,
    inverse_of: :sub
  )



end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :is_moderator?, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def is_moderator?
    sub = Sub.find(params[:id])
    redirect_to sub_url(sub) unless current_user.id == sub.moderator
  end

end

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title%>"%>
  </label>

  <label>
    Description
    <input type="textarea" name="sub[title]" value="<%= @sub.description %>">
  </label>

  <button>Edit sub</button>

</form>

app/views/subs/index.html.erb
<h1>Index</h1>

app/views/subs/new.html.erb
<h1>Create Sub</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= subs_url %>" method="post">
  <%= auth_token %>

  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>"%>
  </label>

  <label>
    Description
    <input type="textarea" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <button>Create sub</button>

</form>

app/views/subs/show.html.erb
<h1><%=@sub.title%></h1>

<h2>Posts:</h2>
<ul>
<% @sub.posts.each do |post|%>
  <li>
    <a href="<%= post_url(post) %>"><%= post.title %></a> |
    <%= post.karma %>
  </li>
  <form action="<%= upvote_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="vote[voteable_id]" value="<%=post.id%>">
    <input type="hidden" name="vote[voteable_type]" value="Post">
    <button>Upvote</button>
  </form>
  <form action="<%= downvote_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="vote[voteable_id]" value="<%=post.id%>">
    <input type="hidden" name="vote[voteable_type]" value="Post">
    <button>Downvote</button>
  </form>


<% end %>
</ul>

<a href="<%= new_post_url %>">Create New Post</a>