config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :subs, except: [:destroy]
  resources :posts, except: [:index] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:index] do
    resources :comments, only: [:new, :create]
  end

  post 'upvote' => 'votes#upvote', as: :upvote
  post 'downvote' => 'votes#downvote', as: :downvote

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :author_id, presence: true

  has_many(
    :post_subs,
    class_name: "PostSub",
    foreign_key: :post_id,
    primary_key: :id,
    inverse_of: :post
  )

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )

  has_many(
    :top_level_comments,
    -> { where("parent_comment_id IS NULL") }, as: :commentable,
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id
  )

  has_many :subs, through: :post_subs, source: :sub

  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id
  )

  has_many :votes, as: :voteable

  def comments_by_parent_id
    result = Hash.new {|hash, key| hash[key] = []}
    self.comments.each do |comment|
      result[comment.parent_comment_id] << comment
    end
    result
  end

  def karma
    karma = 0
    self.votes.each do |vote|
      karma += vote.value
    end
    karma
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @subs = @post.subs
    @comments = @post.comments_by_parent_id
    #@comments = @post.top_level_comments
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids => [])
  end

end

app/views/posts/_comments.html copy.erb
<ul>
<% comments.each do |comment| %>
  <li>
    <%= comment.content %>
    <% if comment.child_comments %>
      <%= render "comments", comments: comment.child_comments %>
    <% end %>
    <a href="<%= new_comment_comment_url(comment) %>">Reply</a>
  </li>
<% end %>
</ul>

app/views/posts/_comments.html.erb
<ul>
<% @comments[c1.id].each do |c2| %>
    <% if c2.parent_comment_id == c1.id %>
        <li><%= c2.content %> |
        <%= c2.author.username%> |
        <%= c2.created_at%>
        </li>
       <a href="<%= new_comment_comment_url(c2) %>">Reply</a>
      <%= render "comments", c1: c2 %>
    <% end %>

<% end %>
</ul>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <%= auth_token %>
  <input type="hidden" name="post[sub_ids][]" value="">

  <label>
    Title
    <input type="text" name="post[title]" value="<%= @post.title%>"%>
  </label>

  <label>
    URL
    <input type="text" name="post[url]" value="<%= @post.url%>"%>
  </label>

  <label>
    Content
    <input type="textarea" name="post[content]" value="<%= @post.content %>">
  </label>

  <label>
    Subs
    <% Sub.all.each do |sub| %>
      <%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
      <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    <% end %>
  </label>

  <button>Update Post</button>

</form>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<form action="<%= posts_url %>" method="post">
  <%= auth_token %>

  <label>
    Title
    <input type="text" name="post[title]" value="<%= @post.title%>"%>
  </label>

  <label>
    URL
    <input type="text" name="post[url]" value="<%= @post.url%>"%>
  </label>

  <label>
    Content
    <input type="textarea" name="post[content]" value="<%= @post.content %>">
  </label>

  <label>
    Subs
    <% Sub.all.each do |sub| %>
      <%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
      <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    <% end %>
  </label>

  <button>Create Post</button>

</form>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<a href="<%= edit_post_url(@post) %>">Edit Post</a>

<h2>Subs</h2>
<ul>
  <% @subs.each do |sub| %>
  <li>
    <%= sub.title %>
  </li>
  <% end %>
</ul>
<br>

<a href="<%= new_post_comment_url(@post.id) %>">New Comment</a>

<h3>Comments</h3>
<ul>
<% @comments[nil].each do |c1| %>
  <li>
    <%= c1.content %> |
    <%= c1.author.username%> |
    <%= c1.created_at%>
    <a href="<%= new_comment_comment_url(c1) %>">Reply</a>
  </li>
  <%= render "comments", c1: c1 %>
<% end %>
</ul>


<a href="<%= user_url(@post.author) %>">Back to User</a>